db:
  build: ../db_chamber
  ports:
   - "3306:3306"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

mq:
  build: ../mq_chamber
  ports:
   - "5672:5672"
   - "15672:15672"
  environment:
    RABBITMQ_DEFAULT_USER: 'root'
    RABBITMQ_DEFAULT_PASS: 'rmflsakdrh'
    RABBITMQ_DEFAULT_VHOST: 'celery'

redis:
  image: redis:2.8.22
  ports:
   - "6379:6379"
