db:
  extends:
    file: ../chamberware/docker-compose.yml
    service: db
    
mq:
  extends:
    file: ../chamberware/docker-compose.yml
    service: mq

redis:
  extends:
    file: ../chamberware/docker-compose.yml
    service: redis

chamber:
  extends:
    file: ../farm_chamber/docker-compose.yml
    service: chamber
  links:
    - db
    - mq
    - redis

swiss:
  extends:
    file: ../farm_chamber/docker-compose.yml
    service: swiss
  links:
    - db
    - mq
    - redis
