db:
  image: mysql:latest
  ports:
   - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 'develop'
    MYSQL_DATABASE: 'develop_cmb'
    MYSQL_USER: 'app_crm'
    MYSQL_PASSWORD: 'Tldkfmdpan'

mq:
  image: rabbitmq:3.5.6-management
  ports:
   - "5672:5672"
   - "15672:15672"
  environment:
    RABBITMQ_DEFAULT_USER: 'app_crm'
    RABBITMQ_DEFAULT_PASS: 'Tldkfmdpan'
    RABBITMQ_DEFAULT_VHOST: 'celery'

redis:
  image: redis:2.8.22
  ports:
   - "6379:6379"

celery_beat:
  build: ../../crm_backoffice
  command: ./run_celery_beat.sh
  volumes:
    - ../../crm_backoffice:/app
  links:
    - db
    - mq
    - redis
  extra_hosts:
    - "crmware:192.168.99.100"
